### ISSUE TITLE
polybar

### ISSUE THREAD

**Issue by yusuf601** [slowy07/my-dotfiles#1]
# Error

mohon maaf saya ingin bertanya apakah di repo my-dotfiles tidak memakai dan polybar hanya memakai bspwm karena saya mencoba config polybar di repo dotfiles dan mengalami error yg saya tidak bisa solve 
![Screenshot from 2024-08-26 18-37-57](https://github.com/user-attachments/assets/1b81068e-23fe-4fde-a4dd-76f39cf2c296)

**Comment by slowy07** [comment]
untuk menjalankan bisa dengan menggunakan perintah

```sh
polybar -c konfigurasi.ini
```
