### ISSUE TITLE
structure direktori nvim dotfiles 

### ISSUE THREAD

**Issue by yusuf601** [slowy07/my-dotfiles#2]
# Structure Directory Nvim in repo dotfiles

## Asslamualaikum saya ingin bertanya mengenai structur nvim yang ada di repositori ini

.
└── ~/.config/nvim/
    ├── core
    ├── costum
    └── lua/
        ├── configs/
        │   └── .semua file lua yg ada file dotfiles my-dotfiles/nvim/plugins/configs
        ├── plugins/
        │   └── semua file .lua yg ada direktori my-dotfiles/nvim/plugins
        ├── chadrc.lua
        ├── mappings.lua
        └── options.lua

saya cukup bingung apakah saya hanya perlu memakai salah satu config yaitu  core atau custom

**Comment by slowy07** [comment]
dari custom bisa @yusuf601 , tapi untuk sekarang bisa pake struktur nvim sekarang
